drop table if exists klienci cascade;
drop table if exists rabaty_stale_klienci cascade;
drop table if exists hasze cascade;
drop table if exists paczkomaty_paczki cascade;
drop table if exists paczkomaty cascade;
drop table if exists paczki cascade;
drop table if exists pojemnosc_paczkomatu cascade;
drop table if exists klasy cascade;
drop table if exists typy cascade;
drop table if exists stany cascade;
drop table if exists cena_klasa_typ cascade;
drop table if exists pracownicy cascade;
drop table if exists historia_paczek cascade;
drop table if exists przewozy cascade;
drop table if exists przewozy_paczki cascade;

drop function if exists insert_hash;
drop function if exists znajdz_pasujace_paczki;
drop function if exists paczkomat_dodaj_check;
drop function if exists wez_za_stare;
drop function if exists pracownik_active;
drop function if exists id_przewozu;
drop function if exists wez_paczki_pracownik;
drop function if exists get_stan_paczki;
drop function if exists get_opis_stanu_paczki;
drop function if exists wloz_paczki_pracownik;
drop function if exists zakoncz_przewoz;
drop function if exists zmien_cena;
drop function if exists zloz_zamowienie;
drop function if exists cena_paczki;
drop function if exists create_przewoz;
drop function if exists odbierz_paczke_klient;
drop function if exists wloz_paczke_klient;
drop function if exists create_klient;
drop function if exists dodaj_rabat;
drop function if exists create_pracownik;
drop function if exists create_paczkomat;
drop function if exists get_moje_paczki_klient;
drop function if exists get_moje_paczki_pracownik;

drop sequence if exists paczki_seq;
drop sequence if exists przewozy_seq;
drop sequence if exists klienci_seq;
drop sequence if exists pracownicy_seq;
drop sequence if exists paczkomaty_seq;